/**
 * This file was generated by farrow-api
 * Don't modify it manually
 */
import { createApiBatchLoader, ApiBatchLoadOptions } from 'farrow-api-client'

/**
 * @label GreetInput
 */
export type GreetInput = {
  /**
   * @remarks The name for greeting
   */
  name: string
}

/**
 * @label GreetOutput
 */
export type GreetOutput = {
  /**
   * @remarks The greeting came from server
   */
  greet: string
}

export const url = 'http://localhost:3003/api/greet'

export const apiBatchLoader = createApiBatchLoader(url)

export const api = {
  /**
   * @remarks Greeting
   */
  greet: (input: GreetInput, options?: ApiBatchLoadOptions) =>
    apiBatchLoader.load({ type: 'Single', path: ['greet'], input }, options) as Promise<GreetOutput>,
}
